<!--<script type="text/ng-template" id="electricModalContent">-->
<script type="text/ng-template" id="electricModalContent">
   <div class="modal-header">
    <h3 class="modal-title" id="modal-title">Свойства</h3>
</div>
<div class="modal-body" id="modal-body">
	<form class="form-inline">
                        <div class="form-group">
			<input class="form-control" ng-model="$ctrl.name" placeholder="Название" required type="text" value="{{ $ctrl.name }}">
                        </div>
        <div class="form-group ml-3">
            <input class="form-control" ng-model="$ctrl.email" placeholder="email" required type="text" value="{{ $ctrl.email }}">
        </div>

    </form>
<br>
	<div class="form-group row margin_0">
		<textarea class="form-control popup_info" ng-model="$ctrl.info">{{$ctrl.info}}}</textarea>
			</div>
    <hr>
    <form class="form-inline">
        <div class="form-group">
            <input class="form-control mr-2" ng-disabled="true" ng-model="$ctrl.geometry.coordinates[0]"
                   placeholder="Широта" required type="text" value="{{ $ctrl.geometry.coordinates[0]}}">
            <input class="form-control" ng-disabled="true" ng-model="$ctrl.geometry.coordinates[1]"
                   placeholder="Долгота" required type="text" value="{{ $ctrl.geometry.coordinates[1] }}">
        </div>

    </form>
	<hr>
    <div class="block" ng-repeat="item in $ctrl.items">
        <form class="form-inline" ng-submit="">
                <select class="form-control col-md-2 mr-2" ng-model="item.type_href" value="{{ item.type_href }}">
                    <option value=img>Изображение</option>
                    <option value=phone>Телефон</option>
                    <option value=email>Email</option>
                    <option value=video>Видеотрансляция</option>
                    <option value=pdf>PDF</option>
                    <option value=url>url</option>
                </select>
                <input class="form-control col-md-3 mr-2 pl-3" ng-model="item.name" placeholder="Имя ссылки" required
                       type="text" value="{{ item.name }}">
                <input class="form-control col-md-3 mr-1 pl-3" ng-model="item.href" placeholder="url" required type="text"
                       value="{{item.href}}">
				<input ng-if="item.type_href == pdf" nv-file-select="" type="file" uploader="uploader"/>
				<button class="btn btn-primary mr-1" type="button"
                        ng-click="$ctrl.objects.update_href($ctrl.id, $ctrl.idfield, item.href, $ctrl.type, item.type_href, item.name, item.id)">Изменить</button>
                <button class="btn btn-danger" type="button"
                        ng-click="$ctrl.objects.delete_href($ctrl.id, $ctrl.idfield, item.id, $ctrl.type, $ctrl.delete_href)">Удалить</button>
        </form>
    </div>
    <div class="block">
    <form class="form-inline" ng-submit="$ctrl.objects.update_href($ctrl.id, $ctrl.idfield, $scope.href, $ctrl.type, $scope.type_href, $scope.name, null, $ctrl.add_href)">
            <select class="form-control col-md-2 mr-2" ng-model="$scope.type_href">
                <option value=img selected>Изображение</option>
                <option value=phone>Телефон</option>
                <option value=email>Email</option>
                <option value=video>Видеотрансляция</option>
                <option value=pdf>PDF</option>
                <option value=url>url</option>
            </select>
			<input class="form-control col-md-3 mr-2 pl-3" ng-model="$scope.name" placeholder="Имя ссылки" required type="text">
                        <input class="form-control col-md-3 mr-1 pl-3" ng-model="$scope.href"
                               placeholder="url" required type="text" ng-if="$scope.type_href !== 'pdf'">
			<input ng-if="$scope.type_href === 'pdf'" nv-file-select="" type="file" uploader="uploader"/>
                        <button class="btn btn-primary" ng-disabled="disabled" type="submit">Добавить</button>

    </form>
    </div>

         <div class="checkbox">
<!--             <label>-->
<!--                 <input type ="checkbox" ng-checked="$ctrl.tool" ng-model="$ctrl.tool"> Есть надпись на карте-->
<!--             </label>-->
             <label ng-hide="$ctrl.type==='Workers'">
                 <input type ="checkbox" ng-model="$ctrl.buildPercentShow"> Процесс застройки
             </label>
             <label ng-hide="$ctrl.type==='Workers'">
                 <input type ="checkbox" ng-model="$ctrl.highlight" ng-click="$ctrl.objects.update($ctrl.id, $ctrl.idfield, $ctrl.type, 'highlight', $ctrl.highlight)"> Выделить на карте
             </label>
         </div>
        <div class="block" ng-repeat="tool in $ctrl.tooltip.hrefs" ng-show="$ctrl.tool">
             <form class="form-inline">
               <input class="form-control col-md-2 mr-2 pl-3"  ng-model="tool.name" placeholder="имя" required type="text">
               <input class="form-control col-md-3 mr-2 pl-3" ng-model="tool.href" placeholder="url" required type="text">
               <button type="submit" class="btn btn-danger" ng-click="$ctrl.DelHref($index)">Удалить</button>
             </form>
        </div>
        <div class="block">
             <form class="form-inline" ng-show="$ctrl.tool">
               <input class="form-control col-md-2 mr-2 pl-3"  ng-model="$ctrl.linkname" placeholder="имя">
               <input class="form-control col-md-3 mr-2 pl-3" ng-model="$ctrl.link" placeholder="url">
               <button type="submit" class="btn btn-primary" ng-disabled="!(($ctrl.linkname)&&($ctrl.link))"
                       ng-click="$ctrl.AddToolRef($ctrl.linkname,$ctrl.link)">Добавить ссылку</button>
             </form>
        </div>
    <div class="block">
         <form name="formPercent" ng-show="$ctrl.buildPercentShow" novalidate>
             Процент застройки <input type="number" ng-model="$ctrl.buildPercent" ng-step="10" ng-min="0" ng-max="100">
             <button type="submit" class="btn btn-primary"
                     ng-disabled="formPercent.$error.step||formPercent.$error.min||formPercent.$error.max"
                     ng-click="$ctrl.objects.update($ctrl.id, $ctrl.idfield, $ctrl.type, 'buildingPercent', $ctrl.buildPercent)">Изменить</button>
             <span class="error" ng-show="formPercent.$error.max"><br>Ошибка! Значение не может быть больше 100</span>
             <span class="error" ng-show="formPercent.$error.min"><br>Ошибка! Значение не может быть меньше 0</span>
             <span class="error" ng-show="formPercent.$error.step"><br>Ошибка! Введите значение кратное 10</span>
         </form>
    </div>
    <div ng-hide="$ctrl.type!=='Workers'">
        <select class="form-control col-md-3 mr-2" ng-model = "$ctrl.workerType">
            <option ng-repeat ="type in $ctrl.workersType" value="{{type._id.$oid}}">{{type.properties.name}}</option>
        </select>
    </div>
</div>

<div class="modal-footer">
    <button class="btn btn-primary" type="button" ng-click="$ctrl.ok()">ОК</button>
</div>
</script>

