<div class="row pl-4 animated fadeIn">
    <table class="table table-responsive-sm table-hover table-sm table-striped">
        <thead> 
            <tr> 
                <th>Автор</th>
                <th>Сообщение</th>
                <th>Решена</th>
                <th>Действия</th>
            </tr>
        </thead> 
        <tbody>
            <tr dir-paginate="mess in messages | itemsPerPage : itemPerPage">
                <td>{{mess.properties.deviceId}}</td>
                <td>{{LimitText(mess.properties.message)}}</td>
                <td>
                <div class="form-check form-check-inline">
                        <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" ng-click="update(mess,'Message','vis',!mess.properties.vis)" ng-model="mess.properties.vis">
                </label>
                </div>    
                </td>
                <th>
                    <button ng-click="open('lg',mess)" type="button" class="btn btn-link">Подробнее</button>
                </th>
            </tr>
        </tbody>
    </table>
    <dir-pagination-controls></dir-pagination-controls>
</div>