<script type="text/ng-template" id="MessageContent">
    <div class="modal-body" id="modal-body">
    <h4 class="modal-title text-center" id="modal-title">{{$ctrl.data.title}}</h4>
    <hr>
    <div class="row">
        <div class="col-md-8">
                        <span> От <span class="label label-info">{{$ctrl.data.from}}</span> в <span class="text text-primary">{{$ctrl.data.time*1000 | date : 'HH:mm:ss yyyy-MM-dd'}}</span>
                             <div class="label label-info" ng-bind-html="workInfo"></div>
                        </span>
       </div>
        <div class="col-md-4" ng-show="$ctrl.admin">
         <span> Решена
            <div class="form-check form-check-inline">
                <label class="form-check-label">
                <input class="form-check-input" type="checkbox" ng-click="$ctrl.update('Message','vis',!$ctrl.data.vis)" ng-model="$ctrl.data.vis">
                </label>
            </div>
        </span>
        </div>
    </div>
    <br>
    <div class="form-group" ng-show="!$ctrl.admin">
        <textarea class="form-control" ng-model="$ctrl.data.message" readonly>
        </textarea>
    </div>
    <div class="form-group" ng-show="$ctrl.admin">
        <textarea class="form-control" ng-model="$ctrl.data.message">
        </textarea>
    </div>

        <div id="video_container" class="d-flex justify-content-center" ng-show="$ctrl.IsVideo" style="height: 450px;">
   <video ng-show="$ctrl.IsVideo" style="max-height: 100%; max-width: 100%" autoplay ="{{$ctrl.IsVideoPlay}}" id="VideoLoc"  controls='true'>
       <source src="{{$ctrl.ZoomVideo.href}}">
   </video>
        </div>
   <div class="row pl-4 pr-4 MediaList" ng-show="$ctrl.IsVideo">
        <div class="card mr-2" ng-repeat="file in $ctrl.video">
            <img class="card-img-top" src="{{file.preview}}" ng-click="$ctrl.Zoom(file)" alt="невозможно загрузить">
        </div>
    </div>
    <hr ng-show="$ctrl.IsVideo">
        <audio width="{{$ctrl.MaxW}}" controls='true' autoplay="{{$ctrl.IsAudioPlay}}" ng-show="$ctrl.IsAudio">
            <source ng-src="{{$ctrl.ZoomAudio.href}}">
            cant load media
        </audio>
   <div class="row pl-4 pr-4 MediaList" ng-show="$ctrl.IsAudio">
        <div class="card mr-2" ng-repeat="file in $ctrl.audio">
            <img class="card-img-top" src="./img/icons/sound.svg" ng-click="$ctrl.Zoom(file)" alt="невозможно загрузить">
        </div>

    </div>

    <hr ng-show="$ctrl.IsAudio">

    <div class="ZoomMedia d-flex align-items-center justify-content-center" style="height:450px" ng-show="$ctrl.IsImage">
        <img style="max-width:100%; max-height: 100%" ng-src="{{$ctrl.ZoomPic.href}}" alt="cant load media">
    </div>
   <div class="row pl-4 pr-4 MediaList" ng-show="$ctrl.IsImage">
        <div class="card mr-2" ng-repeat="file in $ctrl.image">
            <img class="card-img-top" src="{{file.preview}}" ng-click="$ctrl.Zoom(file)" alt="невозможно загрузить">
        </div>
    </div>

</div>
<div class="modal-footer">
    <button class="btn btn-primary" type="button" ng-click="$ctrl.ok('Message','message',$ctrl.data.message)">OK</button>
</div>
    
</script>
