<script type="text/ng-template" id="ovbModalContent">-->
  <div class="modal-header">
    <h3 class="modal-title" id="modal-title">Свойства</h3>
</div>
<div class="modal-body" id="modal-body">
	<div class="form-group row margin_0">
		<textarea class="form-control popup_info"></textarea>
		<input class="btn btn-primary pull-right" ng-disabled="disabled" type="button" ng-click="$ctrl.objects.update_href($ctrl.id, item.href, $ctrl.type, item.type_href, item.name, item.id)" value="Изменить">
	</div>
	<hr>
    <div class="block" ng-repeat="item in $ctrl.items">
        <form class="form-inline" ng-submit="">
            <div class="form-group">
                <select class="form-control" ng-model="item.type_href" value="{{ item.type_href }}">
                    <option value=img>Изображение</option>
                    <option value=phone>Телефон</option>
                    <option value=email>Email</option>
                    <option value=video>Видеотрансляция</option>
                    <option value=pdf>PDF</option>
                    <option value=url>url</option>
                </select>
                <input class="form-control" ng-model="item.name" placeholder="Имя ссылки" required 
                       type="text" value="{{ item.name }}">
                <input class="form-control" ng-model="item.href" placeholder="url" required type="text"
                       value="{{item.href}}">
				<input ng-if="item.type_href == pdf" nv-file-select="" type="file" uploader="uploader"/>
				<button class="btn btn-primary" type="button" ng-click="$ctrl.objects.update_href($ctrl.id, item.href, $ctrl.type, item.type_href, item.name, item.id)">Изменить</button>
                <button class="btn btn-danger" type="button" ng-click="$ctrl.objects.delete_href($ctrl.id, item.id, $ctrl.type, $ctrl.delete_href)">Удалить</button>
            </div>
        </form>
    </div>
    <form class="form-inline" ng-submit="$ctrl.objects.update_href($ctrl.id, href, $ctrl.type, type_href, name, null, $ctrl.add_href)">
        <div class="form-group">
            <select class="form-control" ng-model="type_href">
                <option value=img selected>Изображение</option>
                <option value=phone>Телефон</option>
                <option value=email>Email</option>
                <option value=video>Видеотрансляция</option>
                <option value=pdf>PDF</option>
                <option value=url>url</option>
            </select>
            <input class="form-control" ng-model="name" placeholder="Имя ссылки" required type="text" value="test">
            <input class="form-control" ng-model="href" placeholder="url" required type="text">
            <input class="btn btn-primary" ng-disabled="disabled" type="submit" value="Добавить">
        </div>
    </form>
</div>

<div class="modal-footer">
    <button class="btn btn-primary" type="button" ng-click="$ctrl.ok()">OK</button>
    <!--<button class="btn btn-warning" type="button" ng-click="$ctrl.cancel()">Cancel</button>-->
</div>

</script>
