<div ng-controller="SearchCtrl" class="row pl-4 animated fadeIn">
    <div class="col-md-3 pb-2">
        <div class="card">
          <div class="card-body">
            <form id="search_ps_form" ng-submit="search('Ps', query, pagination.current)">
              <div class="form-group">
                <label for="nf-search">Поиск</label>
                <input type="text" id="search-field" name="nf-search" class="form-control" ng-model="query" placeholder="Техместо">
              </div>
            </form>
          </div>
          <div class="card-footer">
            <button class="btn btn-primary" type="submit" form="search_ps_form" ng-disabled="disabled">
              <i class="fa"></i>Найти</button>
          </div>
        </div>
        <!--<form class="form-inline" ng-submit="search('Ps', query, pagination.current)">-->
                <!--<input class="form-control mb-2 mr-sm-2 mb-sm-0" ng-model="query" placeholder="Техместо" required type="text">-->
                <!--<button class="btn btn-primary" ng-disabled="disabled" type="submit"> Найти </button>-->
        <!--</form>-->

    </div>
    <div class="col-md-9 pr-0">
        <table class="table table-responsive-sm table-hover table-sm table-striped">
            <thead>
                <tr>
                    <th style="width: 5%"></th>
                    <th style="width: 25%">Название</th>
                    <th style="width: 25%">Техместо</th>
                    <th style="width: 25%">Координаты</th>
                    <th style="width: 20%"></th>
                </tr>
            </thead>
            <tbody>
                <tr current-page="pagination.current" dir-paginate="ps in data.items | itemsPerPage: itemPerPage" pagination-id="ps" >
                    <td><i class="fa fa-dot-circle-o" style="color: #0099FF"></i></td>
                    <td>{{ps.properties.d_name}}</td>
                    <td>{{ps.properties.tplnr}}</td>
                    <td>{{ps.geometry.coordinates}}</td>
                    <td>
                        <a class="btn btn-info btn-sm" href="/api/getobjs?format=KML&filename=KML&tplnr={{ps.properties.tplnr}}&type=Ps" role="button">KML</a>
                        <button class="btn btn-danger btn-sm" ng-click="remove('Ps', ps.properties.tplnr)">Удалить</button>
                        <button class="btn btn-primary btn-sm" ng-click="open('lg', ps, 'electric')">Свойства</button>
                    </td>
                </tr>
            </tbody>
        </table>
        <dir-pagination-controls pagination-id="ps"></dir-pagination-controls>
    </div>
</div>

