<script type="text/ng-template" id="resModalContent">
    <div class="modal-header">
        <h3 class="modal-title" id="modal-title">Свойства</h3>
    </div>
    <div class="modal-body" id="modal-body">
        <div class="form-group row margin_0">
            Цвет слоя: <input type="color" ng-model="$ctrl.color" style="width: 100px;">
        </div>
        <hr>
        <div class="modal-footer">
            <button class="btn btn-primary" type="button" ng-click="$ctrl.ok()">OK</button>
        </div>
</script>