<div ng-controller="SearchCtrl" class="row pl-4 animated fadeIn">
    <div class="col-md-3 pb-2">
        <div class="card">
          <div class="card-body">
            <form id="search_worker_form" ng-submit="search('Workers', query)">
              <div class="form-group">
                <label for="nf-search">Поиск</label>
                <input type="text" id="search-field" name="nf-search" class="form-control" ng-model="query" placeholder="Номер IMEI">
              </div>
            </form>
          </div>
          <div class="card-footer">
            <button class="btn btn-primary" type="submit" form="search_worker_form" ng-disabled="disabled">
              <i class="fa"></i>Найти</button>
          </div>
        </div>
        <div class="pt-2">
            <label>Общее сообщение</label>
            <textarea class="form-control block" id="send_message" ng-model="message"></textarea>
            <button class="btn btn-primary btn-block" ng-disabled="disabled" ng-click="send_message(message)">
            Отправить</button>
        </div>
    </div>
    <div class="col-md-9 pr-0">
        <table class="table table-responsive-sm table-hover table-sm table-striped">
            <thead>
                <tr>
                    <th style="width: 5%"></th>
                    <th style="width: 15%">Идентификатор</th>
                    <th style="width: 15%">Имя</th>
                    <th style="width: 20%">Номер</th>
                    <th style="width: 15%">Статус сообщения</th>
                    <th style="width: 15%">Дата</th>
                    <th style="width: 15%"></th>
                </tr>
            </thead>
            <tbody>
                <tr current-page="pagination.current" dir-paginate="workers in data.items | itemsPerPage: itemPerPage" pagination-id="workers">
                    <td><i class="fa fa-dot-circle-o" style="color: #0099FF"></i></td>
                    <td>{{workers.properties.id}}</td>
                    <td>{{workers.properties.name}}</td>
                    <td>{{workers.properties.number}}</td>
                    <td ng-init="st = workers.properties.status">
                        <i class="fa fa-envelope-open fa-fw" ng-if="st == 'read'"></i>
                        <i class="fa fa-envelope fa-fw" ng-if="st == 'delivered'"></i>
                        <i class="fa fa-user-times fa-fw" ng-if="st == 'disconnected'"></i>
                    </td>
                    <td>
                    {{workers.properties.time}}
                    </td>
                    <td >
                        <button ng-show="workers.properties.registration" class="btn btn-danger btn-sm" ng-click="update_obj(workers._id.$oid, '_id','Workers', 'registration' ,false)">Удалить</button>
                        <button ng-show="!workers.properties.registration" class="btn btn-primary btn-sm" ng-click="update_obj(workers._id.$oid, '_id','Workers', 'registration' ,true)">Добавить</button>
                        <button class="btn btn-info btn-sm" ng-click="open('lg', workers, 'electric')">Свойства</button>
                    </td>
                </tr>
            </tbody>
        </table>
        <dir-pagination-controls class="pagination"  pagination-id="workers"></dir-pagination-controls>
    </div>
</div>
