<div ng-controller="SearchCtrl" class="row pl-4  animated fadeIn">
    <div class="col-md-3 pb-2">
    <div class="card">
      <div class="card-body">
        <form id="search_zpt_form" ng-submit="search('Ztp', query, pagination.current)">
          <div class="form-group">
            <label for="nf-search">Поиск</label>
            <input type="text" id="search-field" name="nf-search" class="form-control" ng-model="query" placeholder="Номер заявки">
          </div>
        </form>
      </div>
      <div class="card-footer">
        <button class="btn btn-primary" type="submit" form="search_zpt_form" ng-disabled="disabled">
          <i class="fa"></i>Найти</button>
      </div>
    </div>
  </div>
  <div class="col-md-9 pr-0">
    <table class="table table-responsive-sm table-hover table-sm table-striped">
      <thead>
        <tr>
          <th style="width: 5%"></th>
          <th style="width: 15%">Номер заявки</th>
          <th style="width: 10%">Дата</th>
          <th style="width: 15%">Мощность</th>
          <th style="width: 20%">Статус</th>
          <th style="width: 20%">Координаты</th>
          <th style="width: 10%"></th>
        </tr>
      </thead>
      <tbody>
        <tr current-page="pagination.current" dir-paginate="ztp in data.items | itemsPerPage: itemPerPage" pagination-id="ztp">
          <td><i class="fa fa-dot-circle-o" style="color: #0099FF"></i></td>
          <td>{{ztp.properties.doknr}}</td>
          <td>{{ztp.properties.date}}</td>
          <td>{{ztp.properties.power}}</td>
          <td>{{ztp.properties.status}}</td>
          <td>{{ztp.geometry.coordinates}}</td>
          <td>
            <button class="btn btn-danger btn-sm" ng-click="remove('ztp', ztp.properties.doknr)">Удалить</button>
          </td>
        </tr>
      </tbody>
    </table>
    <dir-pagination-controls  pagination-id="ztp"></dir-pagination-controls>
  </div>
</div>

